export const initialProjects = [
  {
    id: 1,
    parentId: null,
    title: "Build Todolist - React app",
    isComplete: false,
    dateCreated: new Date(),
    dateCompleted: null,
    priority: 1,
  },
  {
    id: 2,
    parentId: null,
    title: "Build Css app",
    isComplete: false,
    dateCreated: new Date(),
    dateCompleted: new Date(),
    priority: 2,
  },
  {
    id: 3,
    parentId: null,
    title: "fill Up Car",
    isComplete: true,
    dateCreated: new Date(),
    dateCompleted: null,
    priority: 2,
  },
  // {
  //   id: 4,
  //   parentId: 1,
  //   title: "1. Build Todolist - Add Sub Projects List on click",
  //   isComplete: false,
  //   dateCreated: new Date(),
  //   dateCompleted: null,
  //   priority: 2,
  // },
  // {
  //   id: 5,
  //   parentId: 1,
  //   title: "2. Build Todolist - On show Sub Project on click ",
  //   isComplete: false,
  //   dateCreated: new Date(),
  //   dateCompleted: null,
  //   priority: 2,
  // },
];
